#!/bin/sh

tput bold
cat <<EOF
Welcome to the RailsBridge virtual machine! The RailsBridge VM is a "computer
within your computer" running the Linux operating system. Everything you need
for the Suggestotron tutorial is installed.

To start your rails server, type

    rails server -b 0.0.0.0

and hit return.

After you start your Rails server, visit http://localhost:3000 in your web browser.

The ~/workspace directory is shared with the folder on your laptop where you
created this VM. Any file you put there in your laptop will appear here in
~/workspace. This lets you edit files with an OSX or Windows text editor, and
run them here in the VM.

To leave the virtual machine, type

    exit

and hit return.
EOF
tput sgr0
